// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbQ6UUy44KVZTQmgvO7MMCzNQehTF0h5Q',
    appId: '1:888642454832:web:f73e00dc81d97eb56774f5',
    messagingSenderId: '888642454832',
    projectId: 'flutterauth-4e130',
    authDomain: 'flutterauth-4e130.firebaseapp.com',
    storageBucket: 'flutterauth-4e130.firebasestorage.app',
    measurementId: 'G-P6CR1FMCQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5tRverm_PP3mA_46ffo_qzvjuaSPngLQ',
    appId: '1:888642454832:android:c30d07f30ef245f16774f5',
    messagingSenderId: '888642454832',
    projectId: 'flutterauth-4e130',
    storageBucket: 'flutterauth-4e130.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQezNtgOCho9wt3OpewXkDiQvnVxE_Y48',
    appId: '1:888642454832:ios:5365833ceda3104a6774f5',
    messagingSenderId: '888642454832',
    projectId: 'flutterauth-4e130',
    storageBucket: 'flutterauth-4e130.firebasestorage.app',
    iosClientId: '888642454832-kf4qaln6doq9bc624tarcjkj79j24af8.apps.googleusercontent.com',
    iosBundleId: 'com.example.hero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQezNtgOCho9wt3OpewXkDiQvnVxE_Y48',
    appId: '1:888642454832:ios:5365833ceda3104a6774f5',
    messagingSenderId: '888642454832',
    projectId: 'flutterauth-4e130',
    storageBucket: 'flutterauth-4e130.firebasestorage.app',
    iosClientId: '888642454832-kf4qaln6doq9bc624tarcjkj79j24af8.apps.googleusercontent.com',
    iosBundleId: 'com.example.hero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbQ6UUy44KVZTQmgvO7MMCzNQehTF0h5Q',
    appId: '1:888642454832:web:cdb6836e839f4cf26774f5',
    messagingSenderId: '888642454832',
    projectId: 'flutterauth-4e130',
    authDomain: 'flutterauth-4e130.firebaseapp.com',
    storageBucket: 'flutterauth-4e130.firebasestorage.app',
    measurementId: 'G-C51X78ZBPR',
  );
}
